name: Metrics

on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Head
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          filename: introduction_stats.svg
          repo: Burn-Detection-Classification
          base: header
          plugin_introduction: yes

      - name: People
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          template: repository
          filename: people.svg
          repo: Burn-Detection-Classification
          plugin_people: yes
          plugin_people_types: contributors, stargazers, watchers, sponsors

